/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApiKeysRouteImport } from './routes/_app/api-keys'
import { Route as AppWorksWorkIdReadIndexRouteImport } from './routes/_app/works.$workId.read.index'
import { Route as AppWorksWorkIdReadPageIdRouteImport } from './routes/_app/works.$workId.read.$pageId'
import { Route as AppWorksWorkIdPagesPageIdRouteImport } from './routes/_app/works.$workId.pages.$pageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppWorksWorkIdReadIndexRoute = AppWorksWorkIdReadIndexRouteImport.update({
  id: '/works/$workId/read/',
  path: '/works/$workId/read/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorksWorkIdReadPageIdRoute =
  AppWorksWorkIdReadPageIdRouteImport.update({
    id: '/works/$workId/read/$pageId',
    path: '/works/$workId/read/$pageId',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorksWorkIdPagesPageIdRoute =
  AppWorksWorkIdPagesPageIdRouteImport.update({
    id: '/works/$workId/pages/$pageId',
    path: '/works/$workId/pages/$pageId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/api-keys': typeof AppApiKeysRoute
  '/works/$workId/pages/$pageId': typeof AppWorksWorkIdPagesPageIdRoute
  '/works/$workId/read/$pageId': typeof AppWorksWorkIdReadPageIdRoute
  '/works/$workId/read/': typeof AppWorksWorkIdReadIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api-keys': typeof AppApiKeysRoute
  '/': typeof AppIndexRoute
  '/works/$workId/pages/$pageId': typeof AppWorksWorkIdPagesPageIdRoute
  '/works/$workId/read/$pageId': typeof AppWorksWorkIdReadPageIdRoute
  '/works/$workId/read': typeof AppWorksWorkIdReadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/': typeof AppIndexRoute
  '/_app/works/$workId/pages/$pageId': typeof AppWorksWorkIdPagesPageIdRoute
  '/_app/works/$workId/read/$pageId': typeof AppWorksWorkIdReadPageIdRoute
  '/_app/works/$workId/read/': typeof AppWorksWorkIdReadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api-keys'
    | '/works/$workId/pages/$pageId'
    | '/works/$workId/read/$pageId'
    | '/works/$workId/read/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api-keys'
    | '/'
    | '/works/$workId/pages/$pageId'
    | '/works/$workId/read/$pageId'
    | '/works/$workId/read'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/api-keys'
    | '/_app/'
    | '/_app/works/$workId/pages/$pageId'
    | '/_app/works/$workId/read/$pageId'
    | '/_app/works/$workId/read/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/works/$workId/read/': {
      id: '/_app/works/$workId/read/'
      path: '/works/$workId/read'
      fullPath: '/works/$workId/read/'
      preLoaderRoute: typeof AppWorksWorkIdReadIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/works/$workId/read/$pageId': {
      id: '/_app/works/$workId/read/$pageId'
      path: '/works/$workId/read/$pageId'
      fullPath: '/works/$workId/read/$pageId'
      preLoaderRoute: typeof AppWorksWorkIdReadPageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/works/$workId/pages/$pageId': {
      id: '/_app/works/$workId/pages/$pageId'
      path: '/works/$workId/pages/$pageId'
      fullPath: '/works/$workId/pages/$pageId'
      preLoaderRoute: typeof AppWorksWorkIdPagesPageIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorksWorkIdPagesPageIdRoute: typeof AppWorksWorkIdPagesPageIdRoute
  AppWorksWorkIdReadPageIdRoute: typeof AppWorksWorkIdReadPageIdRoute
  AppWorksWorkIdReadIndexRoute: typeof AppWorksWorkIdReadIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorksWorkIdPagesPageIdRoute: AppWorksWorkIdPagesPageIdRoute,
  AppWorksWorkIdReadPageIdRoute: AppWorksWorkIdReadPageIdRoute,
  AppWorksWorkIdReadIndexRoute: AppWorksWorkIdReadIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
