/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApiKeysRouteImport } from './routes/_app/api-keys'
import { Route as AppArticlesArticleIdIndexRouteImport } from './routes/_app/articles.$articleId.index'
import { Route as AppArticlesArticleIdReadRouteImport } from './routes/_app/articles.$articleId.read'
import { Route as AppBooksBookIdReadIndexRouteImport } from './routes/_app/books.$bookId.read.index'
import { Route as AppBooksBookIdReadPageIdRouteImport } from './routes/_app/books.$bookId.read.$pageId'
import { Route as AppBooksBookIdPagesPageIdRouteImport } from './routes/_app/books.$bookId.pages.$pageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesArticleIdIndexRoute =
  AppArticlesArticleIdIndexRouteImport.update({
    id: '/articles/$articleId/',
    path: '/articles/$articleId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppArticlesArticleIdReadRoute =
  AppArticlesArticleIdReadRouteImport.update({
    id: '/articles/$articleId/read',
    path: '/articles/$articleId/read',
    getParentRoute: () => AppRoute,
  } as any)
const AppBooksBookIdReadIndexRoute = AppBooksBookIdReadIndexRouteImport.update({
  id: '/books/$bookId/read/',
  path: '/books/$bookId/read/',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksBookIdReadPageIdRoute =
  AppBooksBookIdReadPageIdRouteImport.update({
    id: '/books/$bookId/read/$pageId',
    path: '/books/$bookId/read/$pageId',
    getParentRoute: () => AppRoute,
  } as any)
const AppBooksBookIdPagesPageIdRoute =
  AppBooksBookIdPagesPageIdRouteImport.update({
    id: '/books/$bookId/pages/$pageId',
    path: '/books/$bookId/pages/$pageId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/api-keys': typeof AppApiKeysRoute
  '/articles/$articleId/read': typeof AppArticlesArticleIdReadRoute
  '/articles/$articleId/': typeof AppArticlesArticleIdIndexRoute
  '/books/$bookId/pages/$pageId': typeof AppBooksBookIdPagesPageIdRoute
  '/books/$bookId/read/$pageId': typeof AppBooksBookIdReadPageIdRoute
  '/books/$bookId/read/': typeof AppBooksBookIdReadIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api-keys': typeof AppApiKeysRoute
  '/': typeof AppIndexRoute
  '/articles/$articleId/read': typeof AppArticlesArticleIdReadRoute
  '/articles/$articleId': typeof AppArticlesArticleIdIndexRoute
  '/books/$bookId/pages/$pageId': typeof AppBooksBookIdPagesPageIdRoute
  '/books/$bookId/read/$pageId': typeof AppBooksBookIdReadPageIdRoute
  '/books/$bookId/read': typeof AppBooksBookIdReadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/': typeof AppIndexRoute
  '/_app/articles/$articleId/read': typeof AppArticlesArticleIdReadRoute
  '/_app/articles/$articleId/': typeof AppArticlesArticleIdIndexRoute
  '/_app/books/$bookId/pages/$pageId': typeof AppBooksBookIdPagesPageIdRoute
  '/_app/books/$bookId/read/$pageId': typeof AppBooksBookIdReadPageIdRoute
  '/_app/books/$bookId/read/': typeof AppBooksBookIdReadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api-keys'
    | '/articles/$articleId/read'
    | '/articles/$articleId/'
    | '/books/$bookId/pages/$pageId'
    | '/books/$bookId/read/$pageId'
    | '/books/$bookId/read/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api-keys'
    | '/'
    | '/articles/$articleId/read'
    | '/articles/$articleId'
    | '/books/$bookId/pages/$pageId'
    | '/books/$bookId/read/$pageId'
    | '/books/$bookId/read'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/api-keys'
    | '/_app/'
    | '/_app/articles/$articleId/read'
    | '/_app/articles/$articleId/'
    | '/_app/books/$bookId/pages/$pageId'
    | '/_app/books/$bookId/read/$pageId'
    | '/_app/books/$bookId/read/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles/$articleId/': {
      id: '/_app/articles/$articleId/'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId/'
      preLoaderRoute: typeof AppArticlesArticleIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles/$articleId/read': {
      id: '/_app/articles/$articleId/read'
      path: '/articles/$articleId/read'
      fullPath: '/articles/$articleId/read'
      preLoaderRoute: typeof AppArticlesArticleIdReadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/$bookId/read/': {
      id: '/_app/books/$bookId/read/'
      path: '/books/$bookId/read'
      fullPath: '/books/$bookId/read/'
      preLoaderRoute: typeof AppBooksBookIdReadIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/$bookId/read/$pageId': {
      id: '/_app/books/$bookId/read/$pageId'
      path: '/books/$bookId/read/$pageId'
      fullPath: '/books/$bookId/read/$pageId'
      preLoaderRoute: typeof AppBooksBookIdReadPageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/$bookId/pages/$pageId': {
      id: '/_app/books/$bookId/pages/$pageId'
      path: '/books/$bookId/pages/$pageId'
      fullPath: '/books/$bookId/pages/$pageId'
      preLoaderRoute: typeof AppBooksBookIdPagesPageIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArticlesArticleIdReadRoute: typeof AppArticlesArticleIdReadRoute
  AppArticlesArticleIdIndexRoute: typeof AppArticlesArticleIdIndexRoute
  AppBooksBookIdPagesPageIdRoute: typeof AppBooksBookIdPagesPageIdRoute
  AppBooksBookIdReadPageIdRoute: typeof AppBooksBookIdReadPageIdRoute
  AppBooksBookIdReadIndexRoute: typeof AppBooksBookIdReadIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppIndexRoute: AppIndexRoute,
  AppArticlesArticleIdReadRoute: AppArticlesArticleIdReadRoute,
  AppArticlesArticleIdIndexRoute: AppArticlesArticleIdIndexRoute,
  AppBooksBookIdPagesPageIdRoute: AppBooksBookIdPagesPageIdRoute,
  AppBooksBookIdReadPageIdRoute: AppBooksBookIdReadPageIdRoute,
  AppBooksBookIdReadIndexRoute: AppBooksBookIdReadIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
